{{- if .Values.createGreenDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment-green
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
      version: green
  template:
    metadata:
      labels:
        app: orchestrator
        version: green
    spec:
      containers:
        - name: spring-container
          image: 192.168.0.212:5555/spring-orchestrator:{{ .Values.imageTag }}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: orchestrator-logs
              mountPath: {{ .Values.log.mountPath }}

        - name: fluent-bit
          image: 192.168.0.212:5555/fluent/fluent-bit
          volumeMounts:
            - name: orchestrator-fluent-config
              mountPath: {{ .Values.fluentBit.volume.mountPath }}
              subPath: {{ .Values.fluentBit.volume.subPath }}
            - name: orchestrator-logs
              mountPath: {{ .Values.log.mountPath }}

      volumes:
        - name: orchestrator-logs
          persistentVolumeClaim:
            claimName: orchestrator-logs-pvc-green
        - name: orchestrator-fluent-config
          configMap:
            name: orchestrator-fluent-bit-config-green
{{- end }}