---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orchestrator-logs-pvc-{{ .Values.environment }}
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
