apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: prod
spec:
  selector:
    app: orchestrator
    version: {{ .Values.environment }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentBitService.name }}
  namespace: prod
spec:
  selector:
    app: orchestrator
    version: {{ .Values.environment }}
  ports:
    - name: tcp
      protocol: TCP
      port: 24220
      targetPort: 24224
    - name: udp
      protocol: UDP
      port: 24220
      targetPort: 24224
  type: NodePort